###

GET http://localhost:5087/api/produto/listar

### Buscar produto por nome

GET http://localhost:5087/api/produto/buscar/Mouse
###

POST http://localhost:5087/api/produto/cadastrar
Content-Type: application/json

{
    "nome": "Notebook",
    "quantidade": 123,
    "preco": 85.5
}